repos:
- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
  - id: isort
    name: isort (python)
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pycqa/pylint
  rev: v2.8.2
  hooks:
  - id: pylint
    exclude: "[a-zA-Z]*/(migrations)/(.)*"